### PR TITLE
Resolve #123: Add support for string translation for names, descriptions, and messages

### LINKED ISSUE #123: Add support for string translation for names, descriptions, and messages
As surfaced in https://github.com/php-tuf/composer-stager/pull/118, Drupal requires strings that will appear in user interfaces to be translatable for multilingual support. But it depends on them being defined using its [Localization API](https://www.drupal.org/node/322729), which obviously, Composer Stager knows nothing about. (Nor would it matter, as far as I know, since the code still wouldn't be in the Drupal codebase for discovery.) We need to solve this problem for dependent projects in a way that accounts for the complexity of substitutions, for example.

### Background

> @larowlan, https://github.com/php-tuf/composer-stager/pull/118 - How would downstream users of this go about translating the precondition names/descriptions/unfulfilled/fulfilled strings. For use with e.g. Drupal this would be a requirement I'd think

> @TravisCarden https://github.com/php-tuf/composer-stager/pull/118#issuecomment-1482125783 - This is the hard one, isn't it? I'm glad you bring it up. We discussed it early on, but there wasn't consensus on whether it was actually an issue. I seems to me that it would be a requirement. But as you imply, there are obvious difficulties, and I don't have an easy answer. A few possibilities come readily to my mind:
>
> 1. Composer Stager could provide very specific exception codes (c.f. https://github.com/php-tuf/composer-stager/issues/71), and Drupal could declare its own translatable strings based on them instead of just taking whatever it gets back. The major drawback to this, of course, is that details will be lost, such as error messages that state what went wrong and specify a file it occurred in.
>
> 1. We could add the ability to pass some sort of translation callback into Composer Stager API calls.
>
> 1. Instead of returning strings, we could have Composer Stager return some sort of object that provides placeholder substitution similar to Drupal's `TranslatableMarkup`.

**Related issue:** [Support scanning Composer Stager library for translatable strings [#3354011]](https://www.drupal.org/project/potx/issues/3354011) with the [Translation template extractor (`potx`)](https://www.drupal.org/project/potx).

**Note:** Adding this to https://github.com/php-tuf/composer-stager/milestone/1 as a requirement for a stable release.

### PR DESCRIPTION
**Pull request by TravisCarden**
Resolves #123.

### CODE REVIEW

File: src/Infrastructure/Value/Translation/TranslatableMessage.php [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+{
+    use TranslatableAwareTrait;
+
+    /**
+     * Creates a translatable message.
+     *
+     * @param string $message
+     *   A message containing optional placeholders corresponding to parameters (next). Example:
+     *   ```php
+     *   $message = 'Email %name at <a href="mailto:%email">%email</a>.';
```
Comment (effulgentsia) [inline src/Infrastructure/Value/Translation/TranslatableMessage.php:33]: Within Composer Stager, all translatable messages are text, not HTML. Therefore, let's not use HTML in this example. Let's instead base an example on some message that exists in Composer Stager. +1 though to showing an example message with at least 2 placeholders.

One of the reasons I want to avoid HTML in this example is that in Drupal, you would never use a placeholder that starts with % inside of an HTML attribute value. We have other prefixes for that, but there's no need to complicate Composer Stager by even mentioning those other possible prefixes since there's no use case for them within Composer Stager messages.

**Review by effulgentsia — COMMENTED** [review]
I left 2 comments in this review related to making this more compatible with Drupal's translator.

File: src/Domain/Value/Translation/TranslatableInterface.php [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+    /**
+     * Translates the message.
+     *
+     * @throws \PhpTuf\ComposerStager\Domain\Exception\InvalidArgumentException
+     *   If `$locale` contains invalid characters.
+     */
+    public function trans(TranslatorInterface $translator, ?string $locale = null): string;
+
+    /** Returns the bare message as-given, untranslated, without placeholder substitution. */
+    public function __toString(): string;
```
Comment (effulgentsia) [inline src/Domain/Value/Translation/TranslatableInterface.php:32]: This requirement of __toString() is incompatible with Drupal's TranslatableMarkup, because Drupal's TranslatableMarkup::__toString() returns the translated string (it basically does the same as trans()).

Can we change this Composer Stager interface so that instead of defining __toString() we define a different method (e.g., noTrans()) to return the string in its original language? This can be deferred to a followup issue instead of blocking an initial merge of this PR.
